# Configuration file for the pre-commit tool
# It is used to run tests on CI and on your machine
#
# installation: pip install pre-commit
#
# setup: pre-commit install
#
# Now tests will be run automatically at each commit
# Or you can run the tests with: pre-commit run -a
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.4"
    hooks:
      - id: autopep8
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
      - id: mypy
        args: []
